### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Asuanin** [PatrikValkovic/csfd-api#3]
API vrací chybu u některých filmů, např.
Johanka z Arku: id 14357
Dinotopia:  id 85377
Arn - Templářský rytíř: id 230172

pravděpodobně u výše zmíněných filmů chybí potřebná data nebo se změnila struktura webu

call: API.film(id);
``TypeError: Cannot read property 'replace' of undefined
    at parseLength (/node_modules/csfd-api/lib/parsers/filmParser.js:85:37)
    at Object.module.exports [as film] (/node_modules/csfd-api/lib/parsers/filmParser.js:202:3)
    at Object.csfd.film (/node_modules/csfd-api/lib/csfd.js:36:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
``

node version: v8.11.3
csfd-api version: "1.1.1"

**Comment by PatrikValkovic** [comment]
To je způsobeno tím, že je film/seriál vícedílný (například Johanka z Arku má 2x90min).
Otázka je, jaký je předpokládaný výstup?

**Comment by PatrikValkovic** [comment]
Souhlasíš s opravou v commitu https://github.com/PatrikValkovic/csfd-api/commit/f374c9805f734db67b37b021b7a1ad4b1217781f?

**Comment by Asuanin** [comment]
netestoval jsem to, ale vypadá to dobře

**Comment by PatrikValkovic** [comment]
Zmergováno a publikováno.
