### ISSUE TITLE
Empty results returned from CSFD

### ISSUE THREAD

**Issue by janodvarko** [PatrikValkovic/csfd-api#7]
It looks like something changed on CSFD servers. I am now getting empty results back.
Any tips?
Does this library still works?
Perhaps an issue on my side?

Thanks for any help.

**Comment by PatrikValkovic** [comment]
They redesign the site, so the parsing scripts don't work anymore.
I will look into it in about a week, now I don't have time.

**Comment by PatrikValkovic** [comment]
I decided to deprecate the package, as there is already an alternative: https://www.npmjs.com/package/node-csfd-api

Please use this package instead.
